# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 11:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compositor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compositor', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Compositores',
            },
        ),
        migrations.CreateModel(
            name='etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='instrumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumento', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Instrumentos',
            },
        ),
        migrations.CreateModel(
            name='obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('compositor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='glissando.compositor')),
            ],
            options={
                'verbose_name_plural': 'Obras',
            },
        ),
        migrations.CreateModel(
            name='partitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paritura', models.CharField(max_length=200)),
                ('anotaciones', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('fichero', models.FileField(blank=True, null=True, upload_to='partituras/')),
                ('instrumento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='glissando.instrumento')),
                ('obra', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='glissando.obra')),
            ],
            options={
                'verbose_name_plural': 'Partituras',
            },
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='glissando.etiqueta')),
                ('obra', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='glissando.obra')),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
