# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glissando', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partitura',
            old_name='paritura',
            new_name='partitura',
        ),
    ]
